Demonstrate usage of SWC loader (Updated)
shakacode/react_on_rails_demo_ssr_hmr pull request #56
Opened 2023-06-18 16:02 UTC by ahangarha

This is an up-to-date copy of #30.

I confirm the project works fine (by removing `babel_loader` when we have `webpack_loader: swc` in the config file).

Should we use this as the default setting?

2023-06-21 15:59 UTC, justin808 commented on bin/webpacker
should these files be renamed?

2023-06-21 16:12 UTC, ahangarha commented on bin/webpacker
Since we use Shakapacker 7, yes.

2023-06-22 17:19 UTC, ahangarha commented on bin/webpacker
Done

2023-06-28 15:19 UTC, ahangarha commented
@justin808 Do we need test for this?

2023-07-19 02:39 UTC, Judahmeek requested changes
@ahangarha please add a test or at least documentation on how to run the demo with SWC

2023-09-14 06:37 UTC, justin808 approved these changes

2023-09-26 22:46 UTC, closed without merging